Repository Netcracker/pgskipper-operator, pull requests merged in 2025-07, with the labels that each got.

#63 fix: add affinity for tests
  api/apps/v1/postgresservice_types.go
  api/apps/v1/zz_generated.deepcopy.go
  api/patroni/v1/patronicore_types.go
  api/patroni/v1/zz_generated.deepcopy.go
  charts/patroni-core/crds/qubership.org_patronicores.yaml
  charts/patroni-core/templates/cr.yaml
  charts/patroni-services/crds/qubership.org_patroniservices.yaml
  charts/patroni-services/templates/cr.yaml
  pkg/deployment/tests.go
Labels: bug

#66 feat: Enhance PgBackRest configuration with BackupFromStandby support
  api/apps/v1/postgresservice_types.go
  api/patroni/v1/patronicore_types.go
  charts/patroni-core/templates/cr.yaml
  charts/patroni-services/templates/cr.yaml
  controllers/patroni_core_controller.go
  go.mod
  pkg/deployment/patroni.go
  pkg/deployment/pgbackrest.go
  pkg/helper/patroni_core_helper.go
  pkg/helper/resource_management.go
  pkg/patroni/patroni.go
  pkg/reconciler/backup_daemon.go
  pkg/reconciler/patroni.go
  pkg/upgrade/upgrade.go
  pkg/util/util.go
Labels: enhancement

#70 Feat: add params for backupDaemon
  charts/patroni-services/crds/qubership.org_patroniservices.yaml
  charts/patroni-services/templates/cr.yaml
  charts/patroni-services/values.yaml
  go.mod
  go.sum
Labels: bug, enhancement

#71 fix: encryption type
  charts/patroni-services/crds/qubership.org_patroniservices.yaml
  charts/patroni-services/values.yaml
  go.mod
  go.sum
Labels: bug
